spring:
  thymeleaf:
    cache: true
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/illinois-staging
form-flow:
  aws:
    s3_bucket_name: 'get-child-care-illinois-staging'
  error:
    show-stack-trace: false
  virus-scanning:
    enabled: true
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
