name: Deploy to Aptible Staging

on:
  workflow_run:
    workflows: ["Run tests"]
    types: [completed]
    branches: [main]
  workflow_dispatch:
    inputs: { }

jobs:
  deploy:
    name: Deploy to Aptible Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.APTIBLE_SSH_PRIVATE_KEY }}
      - name: Deploy Using Aptible CLI
        run: |
          ssh-keyscan beta.aptible.com >> ~/.ssh/known_hosts
          wget -O aptible-package https://omnibus-aptible-toolbelt.s3.amazonaws.com/aptible/omnibus-aptible-toolbelt/master/206/pkg/aptible-toolbelt_0.16.5%2B20200508143656~ubuntu.16.04-1_amd64.deb
          sudo dpkg -i aptible-package
          aptible login \
            --email='${{ secrets.APTIBLE_USERNAME }}' \
            --password='${{ secrets.APTIBLE_PASSWORD}}'      
          git push --force ${{ vars.APTIBLE_REMOTE_URL }} ${GITHUB_SHA}:${{ vars.APTIBLE_REMOTE_BRANCH }}   
          aptible deploy \
            --app illinois-get-childcare-staging \
            --git-commitish ${GITHUB_SHA} \
          'AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}' \
          'AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}' \
          'SMARTY_AUTH_ID=${{ secrets.SMARTY_AUTH_ID }}' \
          'SMARTY_AUTH_TOKEN=${{ secrets.SMARTY_AUTH_TOKEN }}' \
          'MAILGUN_KEY=${{ secrets.MAILGUN_KEY }}' \
          'SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}' \
          'SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}' \
          'SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}' \
          'SPRING_PROFILES_ACTIVE=staging' \
          'CLAMAV_URL=${{ vars.CLAMAV_URL }}'
      - name: Announce on Slack when deploy fails
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
